workflows:
  ios-runner-build:
    name: iOS Runner Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Установка зависимостей Flutter
        script: |
          flutter pub get
      - name: Подготовка iOS
        script: |
          flutter build ios --release --no-codesign || true
      - name: Установка зависимостей CocoaPods
        script: |
          cd ios
          pod install
      - name: Сборка iOS-приложения
        script: |
          flutter build ios --release --no-codesign
      - name: Упаковка Runner.app в runner.apa.zip
        script: |
          mkdir -p build/runner
          cp -R build/ios/iphoneos/Runner.app build/runner/
          cd build/runner
          zip -r runner.apa.zip Runner.app
    artifacts:
      - build/runner/runner.apa.zip
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

