workflows:
  flutter-build:
    name: Flutter Build Workflow
    max_build_duration: 120  # Увеличено время сборки
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.myapp"
    scripts:
      - name: Setup Flutter
        script: |
          flutter clean
          flutter pub get
          flutter gen-l10n

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign --verbose

      - name: Build IPA (for distribution)
        script: |
          flutter build ipa --release --no-codesign
          
    artifacts:
      - build/ios/ipa/**/*.ipa
      - build/app/outputs/flutter-apk/**/*.apk
      - build/ios/**/*.xcarchive
      - ios/Podfile.lock
