workflows:
  ios_workflow:  # ⚠️ Это имя должно быть в UI Codemagic
    name: iOS Build
    environment:
      flutter: "stable"
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa

