workflows:
  ios-release-build:
    name: iOS Runner Archive
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Установка зависимостей
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Сборка iOS-архива
        script: |
          flutter build ios --release --no-codesign
      - name: Упаковка runner.apa.zip
        script: |
          mkdir -p build/runner
          cp -R build/ios/iphoneos/Runner.app build/runner/
          cd build/runner
          zip -r runner.apa.zip Runner.app
    artifacts:
      - build/runner/runner.apa.zip
    publishing:
      email:
        recipients:
          - 231549@astanait.edu.kz
          
        notify:
          success: true
          failure: true

