workflows:
  android-ios-workflow:  # Рабочее название workflow (должно совпадать с тем, что вы выбираете в UI Codemagic)
    name: Android & iOS Build
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials  # Группа с вашими ключами подписи (если нужно)
      flutter: "3.22.2"  # Явно указанная версия
      xcode: latest
      cocoapods: default
    
    scripts:
      # 1. Инициализация Flutter
      - name: Flutter Setup
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios

      # 2. Сборка Android
      - name: Build Android APK
        script: |
          flutter build apk --release
          # ИЛИ для App Bundle:
          # flutter build appbundle --release

      # 3. Подготовка iOS
      - name: Prepare iOS
        script: |
          cd ios
          pod repo update
          pod install --repo-update --verbose

      # 4. Сборка iOS
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/**/outputs/**/*.apk  # Android артефакты
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa        # iOS артефакты
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - nukenovdani@gmail.com  # Замените на ваш email
